#' Gets sample parameters of calls
#'
#' @return character vector of selected parameters
#' @export
get_sample_call_parameters <- function() {
  c(
    "pcm_LOGenergy_sma",
    "pcm_zcr_sma" ,
    "voiceprob_sma" ,
    "f0_sma" ,
    "f0env_sma",
    "pcm_fftMag_fband0-250_sma" ,
    "pcm_fftMag_fband0-650_sma",
    "pcm_fftMag_spectralRollOff25_0_sma" ,
    "pcm_fftMag_spectralRollOff50_0_sma",
    "pcm_fftMag_spectralRollOff75_0_sma",
    "pcm_fftMag_spectralRollOff90_0_sma",
    "pcm_fftmag_spectralflux_sma",
    "pcm_fftmag_spectralcentroid_sma" ,
    "pcm_fftmag_spectralmaxpos_sma" ,
    "pcm_fftmag_spectralminpos_sma" ,
    "f0final_sma" ,
    "voicingfinalunclipped_sma",
    "jitterlocal_sma",
    "jitterddp_sma",
    "shimmerlocal_sma",
    "loghnr_sma",
    "audspec_lengthl1norm_sma" ,
    "audspecrasta_lengthl1norm_sma" ,
    "pcm_rmsenergy_sma",
    "audSpec_Rfilt_sma_compare_0_",
    "audSpec_Rfilt_sma_compare_1_" ,
    "audSpec_Rfilt_sma_compare_2_" ,
    "audSpec_Rfilt_sma_compare_3_" ,
    "audSpec_Rfilt_sma_compare_4_",
    "audSpec_Rfilt_sma_compare_5_",
    "audSpec_Rfilt_sma_compare_6_" ,
    "audSpec_Rfilt_sma_compare_7_",
    "audSpec_Rfilt_sma_compare_8_",
    "audSpec_Rfilt_sma_compare_9_",
    "audSpec_Rfilt_sma_compare_10_",
    "audSpec_Rfilt_sma_compare_11_",
    "audSpec_Rfilt_sma_compare_12_",
    "audSpec_Rfilt_sma_compare_13_",
    "audSpec_Rfilt_sma_compare_14_",
    "audSpec_Rfilt_sma_compare_15_" ,
    "audSpec_Rfilt_sma_compare_16_",
    "audSpec_Rfilt_sma_compare_17_",
    "audSpec_Rfilt_sma_compare_18_" ,
    "audSpec_Rfilt_sma_compare_19_" ,
    "audSpec_Rfilt_sma_compare_20_" ,
    "audSpec_Rfilt_sma_compare_21_" ,
    "audSpec_Rfilt_sma_compare_22_" ,
    "audSpec_Rfilt_sma_compare_23_" ,
    "audSpec_Rfilt_sma_compare_24_" ,
    "audSpec_Rfilt_sma_compare_25_",
    "pcm_fftMag_fband250-650_sma_compare" ,
    "pcm_fftMag_fband1000-4000_sma_compare",
    "pcm_fftmag_spectralentropy_sma_compare",
    "pcm_fftmag_spectralvariance_sma_compare" ,
    "pcm_fftmag_spectralskewness_sma_compare",
    "pcm_fftmag_spectralkurtosis_sma_compare" ,
    "pcm_fftmag_psysharpness_sma_compare" ,
    "pcm_fftmag_spectralharmonicity_sma_compare",
    "loudness_sma3",
    "alpharatio_sma3",
    "hammarbergindex_sma3" ,
    "slope0-500_sma3" ,
    "slope500-1500_sma3",
    "F0semitoneFrom27_5Hz_sma3nz",
    "logRelF0-H1-H2_sma3nz",
    "logRelF0-H1-A3_sma3nz" ,
    "f1frequency_sma3nz" ,
    "f1bandwidth_sma3nz" ,
    "f1amplitudelogrelf0_sma3nz" ,
    "f2frequency_sma3nz" ,
    "f2amplitudelogrelf0_sma3nz" ,
    "f3frequency_sma3nz" ,
    "f3amplitudelogrelf0_sma3nz",
    "pcm_fftMag_mfcc_0_" ,
    "pcm_fftMag_mfcc_1_" ,
    "pcm_fftMag_mfcc_2_" ,
    "pcm_fftMag_mfcc_3_",
    "pcm_fftMag_mfcc_4_" ,
    "pcm_fftMag_mfcc_5_" ,
    "pcm_fftMag_mfcc_6_",
    "pcm_fftMag_mfcc_7_",
    "pcm_fftMag_mfcc_8_",
    "pcm_fftMag_mfcc_9_",
    "pcm_fftMag_mfcc_10_",
    "pcm_fftMag_mfcc_11_",
    "pcm_fftMag_mfcc_12_"
  )
}
